### ISSUE TITLE
Bring in UA-specific migrations

### ISSUE THREAD

**Issue by str4d** [zcash-hackworks/zcash-light-client-ffi#18]
#15 will enable new wallets generated by this library to be compatible with UAs. Existing wallets will require database migrations, which can't be brought in until after #16.

Depending on how https://github.com/zcash/librustzcash/issues/489 goes, this issue might end up being a no-op if we duplicate the migrations in Swift for https://github.com/zcash/ZcashLightClientKit/issues/391.

**Comment by nuttycom** [comment]
Closed via merge of #45
