### ISSUE TITLE
Remove accountId from UnifiedFullViewingKey FFI representation

### ISSUE THREAD

**Issue by pacu** [zcash-hackworks/zcash-light-client-ffi#41]
Per this PR https://github.com/zcash/librustzcash/pull/625/files#diff-49f5696553e6939b88b1d7bcda0170f1f03715076ec3ee1c70b267345a55cfd1L82

````
typedef struct {
  uint32_t account_id;
  const char *encoding;
} FFIEncodedKey;
````

**Comment by pacu** [comment]
@nuttycom @str4d  what should we do about this?

**Comment by nuttycom** [comment]
At the FFI layer, we don't need to change anything; the current data structure is effectively just a tuple of the account ID and the key, but that tuple shouldn't be considered the same as the UnifiedFullViewingKey type.
