### ISSUE TITLE
[0.1.0-beta.1] SaplingBuild(AnchorMismatch) when 2 transactions in a row

### ISSUE THREAD

**Issue by pacu** [zcash-hackworks/zcash-light-client-ffi#61]
![image](https://user-images.githubusercontent.com/484008/198674094-64d5f23a-d4ef-4e68-a141-9b02d2606cc5.png)

Reproduce

- with more than 1 note
- send funds that would leave available balance for a subsequent transaction
- after balance has updated send another transaction

expected: both transactions should be created w/o problems
result: second transaction fails (see image above)

update 1: quick-rescan to oldest unspent note does not fix it

update 2: wiping the wallet and rescanning does not fix it either.

**Comment by nuttycom** [comment]
I've tracked the issue down to this: https://github.com/zcash/librustzcash/blob/main/zcash_client_backend/src/data_api/wallet.rs#L310-L314

This is not going to do the right thing when using change notes.
